### ISSUE TITLE
Extract Error

### ISSUE THREAD

**Issue by kloruklass** [wowsinfo/wowsunpack#17]
I keep getting the following error:
![Screen](https://user-images.githubusercontent.com/78429737/205487601-9aebc62d-795e-4a1b-a890-4d154fb0439c.png)

**Comment by HenryQuan** [comment]
Can you send me your game path?

**Comment by kloruklass** [comment]
This: D:\Games\World_of_Warships

**Comment by HenryQuan** [comment]
This crash is coming from the official tool. This happened once when the path contains spaces, but our path seems legit to me. 
This may also happen when the game has downloaded an update. This is not yet handled in the python implementation.

**Comment by kloruklass** [comment]
I actually have Win10, but anyway thanks for taking a look.
I just downloaded the game from Steam, maybe it's because of that.

**Comment by HenryQuan** [comment]
Thanks, steam version might be different. Can you send me the folder structure of the game, mainly the bin folder. Maybe, res_package folder is placed elsewhere.

**Comment by kloruklass** [comment]
Here's the folder structure of the game and relative files:
[Folder_Structure.txt](https://github.com/wowsinfo/wowsunpack/files/10149494/Folder_Structure.txt)

Thanks in advance!

**Comment by HenryQuan** [comment]
Thanks for providing the structure. I have looked into it, and it is identical with to the non-steam version. Not sure what triggers the crash. I will have a try later today.

**Comment by kloruklass** [comment]
Is it possible that I have to install something to run it properly? Just throwing some ideas.

Thanks for helping!

**Comment by kloruklass** [comment]
I tried with another PC but it's giving the same mistake.
Here's the screen: ![Screen](https://user-images.githubusercontent.com/78429737/205695547-b9503f88-6b66-4884-8723-52740e733804.png)

**Comment by kloruklass** [comment]
Sooo, after updating the game I tried once more and everything worked fine!
I think it was because some files were missing or corrupted.

Thanks a lot for having a look into this, I should have tried in the first place.

**Comment by kloruklass** [comment]
Sooo, after updating the game I tried once more and everything worked fine!
I think it was because some files were missing or corrupted.

Thanks a lot for having a look into this, I should have done it before.
